eSanjeevaniIcuPortal/eSanjeevaniIcu.Portal/Models/PatientDetailsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace eSanjeevaniIcu.Portal.Models
{
    public class PatientDetailsViewModel
    {
        public int PatientDetailId { get; set; }

        public int PatientId { get; set; }
        public string PatientName { get; set; }

        public DateTime Date { get; set; }

        public decimal? Temperature { get; set; }

        public decimal? RrRespiratoryRate { get; set; }

        public decimal? OxygenSaturationSpo2 { get; set; }

        public decimal? BloodPressureDia { get; set; }

        public decimal? BloodPressureSys { get; set; }

        public decimal? HeartRate { get; set; }

        public int? PatientStatus { get; set; }
        public string PatientStatusName { get; set; }

        public DateTime CreatedOn { get; set; }

        public int CreatedBy { get; set; }
        public string CreatedByName { get; set; }

        public DateTime? LastUpdatedOn { get; set; }

        public int? LastUpdatedBy { get; set; }

        public bool Status { get; set; }
        public string StatusName { get; set; }
        public List<SelectListItem> lstPatientMaster { get; set; }
        public List<SelectListItem> lstPatientStatus { get; set; }
        public List<PatientDetailsViewModel> lstPatientDetailsViewModel { get; set; }
    }
}

eSanjeevaniIcuPortal/eSanjeevaniIcu.Portal/Controllers/PatientDetailsController.cs
using eSanjeevaniIcu.Data.eSanjeevaniIcuDBEntities;
using eSanjeevaniIcu.Portal.Filters;
using eSanjeevaniIcu.Portal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eSanjeevaniIcu.Portal.Controllers
{
    [SessionTimeoutAttribute]
    public class PatientDetailsController : Controller
    {
        private readonly eSanjeevaniIcuDbContext _context;

        public PatientDetailsController(eSanjeevaniIcuDbContext context)
        {
            _context = context;
        }

        // GET: MenuMasters
        public ActionResult Index()
        {
            PatientDetailsViewModel patientDetailsViewModel = new PatientDetailsViewModel();
            try
            {
                //var lstPatientMaster = _context.TbPatientMasters.Where(x => x.Status == true).Select(s => new SelectListItem { Value = s.PatientId.ToString(), Text = s.PatientName }).ToList();
                patientDetailsViewModel.lstPatientDetailsViewModel = (from patientDetails in _context.TbPatientDetails
                                                                      join patientMaster in _context.TbPatientMasters on patientDetails.PatientId equals patientMaster.PatientId
                                                                      where patientDetails.Status == true
                                                                      select new PatientDetailsViewModel
                                                                      {
                                                                          PatientDetailId = patientDetails.PatientDetailId,
                                                                          PatientId = patientDetails.PatientId,
                                                                          PatientName = patientMaster.PatientName,
                                                                          Date = patientDetails.Date,
                                                                          StatusName = patientDetails.Status == true ? "Active" : "Inactive",
                                                                      }).ToList();
                patientDetailsViewModel.lstPatientDetailsViewModel = patientDetailsViewModel.lstPatientDetailsViewModel.GroupBy(g => new { g.PatientId, g.Date }).Select(s => s.Last()).ToList();
            }
            catch (Exception ex)
            {
                string message = ex.Message.ToString();
                patientDetailsViewModel.lstPatientDetailsViewModel = new List<PatientDetailsViewModel>();
                return View(patientDetailsViewModel);
            }
            return View(patientDetailsViewModel);
        }


        public async Task<IActionResult> Details(int? id, DateTime dt)
        {
            PatientDetailsViewModel patientDetailsViewModel = new PatientDetailsViewModel();
            try
            {
                patientDetailsViewModel.lstPatientStatus = _context.TbPatientStatuses.Where(x => x.Status == true).Select(s => new SelectListItem { Value = s.PatientStatusId.ToString(), Text = s.PatientStatusName }).ToList();

                patientDetailsViewModel.lstPatientDetailsViewModel = (from patientDetails in _context.TbPatientDetails
                                                                      join patientMaster in _context.TbPatientMasters on patientDetails.PatientId equals patientMaster.PatientId
                                                                      join userMaster in _context.TbUserMasters on patientMaster.CreatedBy equals userMaster.UserId
                                                                      where patientDetails.PatientId == id && patientDetails.Date == dt
                                                                      select new PatientDetailsViewModel
                                                                      {
                                                                          PatientDetailId = patientDetails.PatientDetailId,
                                                                          PatientId = patientDetails.PatientId,
                                                                          PatientName = patientMaster.PatientName,
                                                                          Date = patientDetails.Date,
                                                                          Temperature = patientDetails.Temperature,
                                                                          RrRespiratoryRate = patientDetails.RrRespiratoryRate,
                                                                          OxygenSaturationSpo2 = patientDetails.OxygenSaturationSpo2,
                                                                          BloodPressureDia = patientDetails.BloodPressureDia,
                                                                          BloodPressureSys = patientDetails.BloodPressureSys,
                                                                          HeartRate = patientDetails.HeartRate,
                                                                          PatientStatus = patientDetails.PatientStatus,
                                                                          PatientStatusName = "",//lstPatientStatus.Where(x => Convert.ToInt32(x.Value) == Convert.ToInt32(patientDetails.PatientStatus)).Select(s => s.Text).FirstOrDefault(),
                                                                          CreatedOn = patientDetails.CreatedOn,
                                                                          CreatedByName = userMaster.LastName != null ? (userMaster.FirstName + " " + userMaster.LastName) : userMaster.FirstName,
                                                                          StatusName = patientDetails.Status == true ? "Active" : "Inactive",
                                                                      }).ToList();
                patientDetailsViewModel.Date = patientDetailsViewModel.lstPatientDetailsViewModel.FirstOrDefault().Date;
                patientDetailsViewModel.PatientId = patientDetailsViewModel.lstPatientDetailsViewModel.FirstOrDefault().PatientId;
                patientDetailsViewModel.PatientName = patientDetailsViewModel.lstPatientDetailsViewModel.FirstOrDefault().PatientName;
                patientDetailsViewModel.CreatedByName = patientDetailsViewModel.lstPatientDetailsViewModel.FirstOrDefault().CreatedByName;

            }
            catch (Exception ex)
            {
                string message = ex.Message.ToString();
                patientDetailsViewModel.lstPatientDetailsViewModel = new List<PatientDetailsViewModel>();
                return View(patientDetailsViewModel);
            }
            return View(patientDetailsViewModel);
        }

        // GET: MenuMasters/Create
        public IActionResult Create()
        {
            PatientDetailsViewModel patientDetailsViewModel = new PatientDetailsViewModel();
            try
            {
                patientDetailsViewModel.Date = DateTime.Now.Date;
                patientDetailsViewModel.lstPatientMaster = _context.TbPatientMasters.Where(x => x.Status == true).Select(s => new SelectListItem { Value = s.PatientId.ToString(), Text = s.PatientName }).ToList();
                patientDetailsViewModel.lstPatientStatus = _context.TbPatientStatuses.Where(x => x.Status == true).Select(s => new SelectListItem { Value = s.PatientStatusId.ToString(), Text = s.PatientStatusName }).ToList();
            }
            catch (Exception ex)
            {
                patientDetailsViewModel.lstPatientMaster = new List<SelectListItem>();
                patientDetailsViewModel.lstPatientStatus = new List<SelectListItem>();
                return View(patientDetailsViewModel);
            }
            return View(patientDetailsViewModel);
        }

        [HttpPost]
        public JsonResult Create(List<PatientDetailsViewModel> lstPatientDetailsViewModel)
        {
            using (var transation = _context.Database.BeginTransaction())
            {
                try
                {
                    List<TbPatientDetail> lstTbPatientDetails = new List<TbPatientDetail>();
                    foreach (var item in lstPatientDetailsViewModel)
                    {
                        TbPatientDetail tbPatientDetail = new TbPatientDetail();
                        tbPatientDetail.PatientId = item.PatientId;
                        tbPatientDetail.Date = item.Date;
                        tbPatientDetail.Temperature = item.Temperature;
                        tbPatientDetail.RrRespiratoryRate = item.RrRespiratoryRate;
                        tbPatientDetail.OxygenSaturationSpo2 = item.OxygenSaturationSpo2;
                        tbPatientDetail.BloodPressureDia = item.BloodPressureDia;
                        tbPatientDetail.BloodPressureSys = item.BloodPressureSys;
                        tbPatientDetail.HeartRate = item.HeartRate;
                        tbPatientDetail.PatientStatus = item.PatientStatus;
                        tbPatientDetail.CreatedOn = DateTime.Now;
                        tbPatientDetail.CreatedBy = HttpContext.Session.GetInt32(Common.PrincipalId) ?? 0;
                        tbPatientDetail.Status = true;
                        lstTbPatientDetails.Add(tbPatientDetail);
                    }
                    _context.TbPatientDetails.AddRange(lstTbPatientDetails);
                    _context.SaveChanges();
                    transation.Commit();
                }
                catch (Exception ex)
                {
                    transation.Rollback();

eSanjeevaniIcuPortal/eSanjeevaniIcu.Portal/Views/PatientDetails/Create.cshtml
@model eSanjeevaniIcu.Portal.Models.PatientDetailsViewModel
@using Microsoft.Extensions.Options;
@using eSanjeevaniIcu.Portal.Controllers;
@inject IOptions<ApplicationConfigurations> OptionsApplicationConfiguration
@{
    string apiUrl = @OptionsApplicationConfiguration.Value.ApplicationHostUrl;
    ViewData["Title"] = "Patient Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/sweet-alert.css" rel="stylesheet" />
<script src="~/js/sweet-alert.js"></script>
<div class="PageBorder">
    <div class="row">
        <div class="col-md-12">
            <div class="table color-table PageTitle">
                Create Patient Details
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-6">
                <label>Patient<span class="text-dangar">*</span></label>
                @Html.DropDownListFor(m => m.PatientId, Model.lstPatientMaster, "Select Patient", new { @class = "form-control", @name = "ddlPatientMaster", ID = "ddlPatientMaster" })
                <span id="spnPatient" class="text-dangar" style="display:none">Patient is required.</span>
            </div>
            <div class="col-md-6">
                <label>Date<span class="text-dangar">*</span></label>
                <input type="date" asp-for="Date" class="form-control" id="dtDate" />
                <span id="spnDate" class="text-dangar" style="display:none">Date is required.</span>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12 bg-red mb-10 mt-4">
                <div class="row align-items-center PageTitle">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area1 clearfix">
                            <h4 class="page-title1 pull-left font-18">Patient Data</h4>
                        </div>

                    </div>
                    <div class="col-sm-6 fr">
                        <i class="fa fa-plus-circle addsection pull-right"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table color-table">
                    <thead class="">
                        <tr>
                            <th>Temprature<span class="text-dangar"></span></th>
                            <th>Respiratory Rate<span class="text-dangar"></span></th>
                            <th>Oxygen Saturation<span class="text-dangar"></span></th>
                            <th>Blood Pressure DIA<span class="text-dangar"></span></th>
                            <th>Blood Pressure SYS<span class="text-dangar"></span></th>
                            <th>Heart Rate<span class="text-dangar"></span></th>
                            <th>PatientStatus<span class="text-dangar"></span></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="sections">
                        <tr class="section">
                            <td style="display:none">
                                <input type="hidden" id="hdnPatientDetailId" value="0" />
                            </td>
                            <td>
                                <input type="number" id="txtTemprature" maxlength="10" IsTemprature="true" class="form-control clsTemprature" />
                                <span class="text-dangar spnTemprature" style="display:none">Temprature is required.</span>
                            </td>
                            <td>
                                <input type="number" id="txtRespiratoryRate" maxlength="10" IsRespiratoryRate="true" class="form-control clsRespiratoryRate" />
                                <span class="text-dangar spnRespiratoryRate" style="display:none">Respiratory Rate is required.</span>
                            </td>
                            <td>
                                <input type="number" id="txtOxygenSaturation" maxlength="10" IsOxygenSaturation="true" class="form-control clsOxygenSaturation" />
                                <span class="text-dangar spnOxygenSaturation" style="display:none">Oxygen Saturation is required.</span>
                            </td>
                            <td>
                                <input type="number" id="txtBloodPressureDIA" maxlength="10" IsBloodPressureDIA="true" class="form-control clsBloodPressureDIA" />
                                <span class="text-dangar spnBloodPressureDIA" style="display:none">Blood Pressure DIA is required.</span>
                            </td>
                            <td>
                                <input type="number" id="txtBloodPressureSYS" maxlength="10" IsBloodPressureSYS="true" class="form-control clsBloodPressureSYS" />
                                <span class="text-dangar spnBloodPressureSYS" style="display:none">Blood Pressure SYS is required.</span>
                            </td>
                            <td>
                                <input type="number" id="txtHeartRate" maxlength="10" IsHeartRate="true" class="form-control clsHeartRate" />
                                <span class="text-dangar spnHeartRate" style="display:none">Heart Rate is required.</span>
                            </td>
                            <td>
                                @Html.DropDownListFor(m => m.PatientStatus, Model.lstPatientStatus, "Select Patient Status", new { @class = "form-control", @name = "ddlPatientStatus", ID = "ddlPatientStatus" })
                                <span class="text-dangar spnPatientStatus" style="display:none">Patient Status is required.</span>
                            </td>
                            <td>
                                <a href="#" class="remove btn btn-primary"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-12 mt-4 mb-5" style="margin-top:20px">

            <input type="submit" value="Save" class="btn btn-primary" id="btnSave" />

            <a asp-action="Index" class="btn btn-primary">Back to List</a>
        </div>
    </div>
</div>

<script>
    var newRow = $("#sections .section:first").clone();
    var rowCount = 1;
    $(".addsection").click(function () {
        rowCount++;
        newRow.clone().find(':input').each(function () {
            var newId = this.id + rowCount;
            $(this).prev().attr('for', newId);
            this.id = newId;
            $(this).val("");
        }).end()
            .appendTo("#sections");
        return false;
    });
    //-- Add Row End--//
    //---Remove Row Start--//
    $("#sections").on('click', '.remove', function () {
        $(this).closest('tr').remove();
        rowCount--;
        SubTotal();
        return false;
    })
    //--Remove Row End--//


    function validateControls() {
        var result = true;

        if ($("#ddlPatientMaster option:selected").val() == "") {
            $("#spnPatient").attr("style", "display:inline-block");
            result = false;
        }
        else {
            $("#spnPatient").attr("style", "display:none");
        }
        if ($("#dtDate").val() == "") {
            $("#spnDate").attr("style", "display:inline-block");
            result = false;
        }
        else {
            $("#spnDate").attr("style", "display:none");
        }

        $(".section").each(function () {
            if ($(this).find('td:eq(1)').find('input').val() == "") {
                $(this).find('td:eq(1)').find('span').show();
                result = false;
            }
            else {
                $(this).find('td:eq(1)').find('span').hide();
            }

            if ($(this).find('td:eq(2)').find('input').val() == "") {
                $(this).find('td:eq(2)').find('span').show();
                result = false;
            }
            else {
                $(this).find('td:eq(2)').find('span').hide();
            }

            if ($(this).find('td:eq(3)').find('input').val() == "") {
                $(this).find('td:eq(3)').find('span').show();
                result = false;
            }
            else {
                $(this).find('td:eq(3)').find('span').hide();
            }

            if ($(this).find('td:eq(4)').find('input').val() == "") {
                $(this).find('td:eq(4)').find('span').show();
                result = false;
            }
            else {
                $(this).find('td:eq(4)').find('span').hide();
            }

            if ($(this).find('td:eq(5)').find('input').val() == "") {
                $(this).find('td:eq(5)').find('span').show();
                result = false;
            }
            else {
                $(this).find('td:eq(5)').find('span').hide();
            }

            if ($(this).find('td:eq(6)').find('input').val() == "") {
                $(this).find('td:eq(6)').find('span').show();
                result = false;
            }
            else {
                $(this).find('td:eq(6)').find('span').hide();
            }

            if ($(this).find('td:eq(7)').find('select option:selected').val() == "") {
                $(this).find('td:eq(7)').find('span').show();
                result = false;
            }
            else {
                $(this).find('td:eq(7)').find('span').hide();
            }
        })
        return result;
    }

    function GetPatientDetailData() {
        var patientDetailViewModel = [];

        $(".section").each(function () {
            var detailViewModel = {
                patientDetailId: 0,
                patientId: $("#ddlPatientMaster option:selected").val(),
                date: $("#dtDate").val(),
                temperature: null,
                rrRespiratoryRate: null,
                oxygenSaturationSpo2: null,
                bloodPressureDia: null,
                bloodPressureSys: null,
                heartRate: null,
                patientStatus: null
            }
            detailViewModel.temperature = $(this).find('td:eq(1)').find('input').val();
            detailViewModel.rrRespiratoryRate = $(this).find('td:eq(2)').find('input').val();
            detailViewModel.oxygenSaturationSpo2 = $(this).find('td:eq(3)').find('input').val();
            detailViewModel.bloodPressureDia = $(this).find('td:eq(4)').find('input').val();
            detailViewModel.bloodPressureSys = $(this).find('td:eq(5)').find('input').val();
            detailViewModel.heartRate = $(this).find('td:eq(6)').find('input').val();
            detailViewModel.patientStatus = $(this).find('td:eq(7)').find('select option:selected').val();
            patientDetailViewModel.push(detailViewModel);
        })
        return patientDetailViewModel;
    }

    $("#btnSave").click(function () {
        if (validateControls()) {
            var patientDetailViewModel = GetPatientDetailData();
            var url = '@apiUrl';
            url += "/PatientDetails/Create";
            $.ajax({
                url: url,
                type: "POST",
                dataType: "Json",
                data: { lstPatientDetailsViewModel: patientDetailViewModel },
                success: function (response) {
                    if (response.success) {
                        swal("Success", response.responseText, "success");
                        location.href = '@Url.Action("Index", "PatientDetails")';
                    }
                    else {
                        swal("Error", response.responseText, "error");
                    }

                },
                error: function (errormessage) {
                    swal("Error", errormessage.responseText, "error");
                }
            })
        }
        else {
            return;
        }
    })
</script>

eSanjeevaniIcuPortal/eSanjeevaniIcu.Portal/Views/PatientDetails/Delete.cshtml
@model eSanjeevaniIcu.Portal.Models.PatientDetailsViewModel
@using Microsoft.Extensions.Options;
@using eSanjeevaniIcu.Portal.Controllers;
@inject IOptions<ApplicationConfigurations> OptionsApplicationConfiguration
@{
    string apiUrl = @OptionsApplicationConfiguration.Value.ApplicationHostUrl;
    ViewData["Title"] = "Patient Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/sweet-alert.css" rel="stylesheet" />
<script src="~/js/sweet-alert.js"></script>
<div class="PageBorder">
    <div class="row">
        <div class="col-md-12">
            <div class="table color-table PageTitle">
                Delete Patient Details
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <h4>Are you sure you want to delete this?</h4>
        <div class="row">
            <dl>
                <dt class="col-md-3">Patient Name</dt>
                <dd class="col-md-9">: @Model.PatientName</dd>
                <dt class="col-md-3">Date</dt>
                <dd class="col-md-9">: @Model.Date.ToString("dd-MM-yyyy")</dd>
                <dt class="col-md-3">Created On</dt>
                <dd class="col-md-9">: @Model.CreatedOn.ToString("dd-MM-yyyy")</dd>
                <dt class="col-md-3">Created By</dt>
                <dd class="col-md-9">: @Model.CreatedByName</dd>
            </dl>
        </div>

        <div class="row">
            <div class="col-md-12 bg-red mb-10 mt-4">
                <div class="row align-items-center PageTitle">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area1 clearfix">
                            <h4 class="page-title1 pull-left font-18">Patient Data</h4>
                        </div>

                    </div>
                    <div class="col-sm-6 fr">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table color-table">
                    <thead class="">
                        <tr>
                            <th>Temprature<span class="text-dangar"></span></th>
                            <th>Respiratory Rate<span class="text-dangar"></span></th>
                            <th>Oxygen Saturation<span class="text-dangar"></span></th>
                            <th>Blood Pressure DIA<span class="text-dangar"></span></th>
                            <th>Blood Pressure SYS<span class="text-dangar"></span></th>
                            <th>Heart Rate<span class="text-dangar"></span></th>
                            <th>PatientStatus<span class="text-dangar"></span></th>
                        </tr>
                    </thead>
                    <tbody id="sections">
                        @if (Model.lstPatientDetailsViewModel != null && Model.lstPatientDetailsViewModel.Count > 0)
                        {
                            foreach (var item in Model.lstPatientDetailsViewModel)
                            {
                                <tr class="section">
                                    <td style="display:none">
                                        <input type="hidden" id="hdnPatientDetailId" value="@item.PatientDetailId" />
                                    </td>
                                    <td>@item.Temperature </td>
                                    <td>@item.RrRespiratoryRate </td>
                                    <td>@item.OxygenSaturationSpo2 </td>
                                    <td>@item.BloodPressureDia </td>
                                    <td>@item.BloodPressureSys </td>
                                    <td>@item.HeartRate </td>
                                    <td>@Model.lstPatientStatus.Where(x=>x.Value==item.PatientStatus.ToString()).Select(s=>s.Text).FirstOrDefault() </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-12 mt-4 last-row" style="margin-top:20px">

            <input type="hidden" id="hdnDate" value="@Model.Date.ToString("yyyy-MM-dd")" />
            <input type="hidden" id="hdnPatientId" value="@Model.PatientId" />
            <a title="Delete" onclick="DeletePatientDetail(this)" class="btn btn-primary">Delete</a>
            <a asp-action="Index" class="btn btn-primary">Back to List</a>
        </div>
    </div>

</div>
<script>
    function DeletePatientDetail(eve) {
        var patientId = $('#hdnPatientId').val();
        var daDate = $('#hdnDate').val();
        var url = '@apiUrl';
        url += "/PatientDetails/DeleteConfirmed/";
        $.ajax({
            type: "POST",
            cache: false,
            url: url,
            data: { id: patientId, dt: daDate },
            success: function (response) {
                swal("Success", response.responseText, "success");
                location.href = '@Url.Action("Index", "PatientDetails")';
            }
        })
    }
</script>